// <auto-generated />
using MVCZoo2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCZoo2.Migrations
{
    [DbContext(typeof(MVCZoo2Context))]
    [Migration("20190929154806_Zoo")]
    partial class Zoo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCZoo2.Models.Especie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<string>("Foto");

                    b.Property<string>("NombreCientifico");

                    b.Property<string>("NombreCompuesto");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("MVCZoo2.Models.Habitat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clima");

                    b.Property<int>("ItinerarioId");

                    b.Property<string>("Nombre");

                    b.Property<string>("Vegetacion");

                    b.HasKey("Id");

                    b.HasIndex("ItinerarioId");

                    b.ToTable("Habitats");
                });

            modelBuilder.Entity("MVCZoo2.Models.Itinerario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<int>("Duracion");

                    b.Property<double>("Longitud");

                    b.Property<int>("Visitantes");

                    b.HasKey("Id");

                    b.ToTable("Itinerarios");
                });

            modelBuilder.Entity("MVCZoo2.Models.ViveEn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EspecieId");

                    b.Property<int>("HabitatId");

                    b.Property<int>("Indice");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("HabitatId");

                    b.ToTable("ViveEns");
                });

            modelBuilder.Entity("MVCZoo2.Models.Habitat", b =>
                {
                    b.HasOne("MVCZoo2.Models.Itinerario", "Itinerarios")
                        .WithMany("Habitats")
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MVCZoo2.Models.ViveEn", b =>
                {
                    b.HasOne("MVCZoo2.Models.Especie", "Especie")
                        .WithMany("ViveEns")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MVCZoo2.Models.Habitat", "Habitat")
                        .WithMany("ViveEns")
                        .HasForeignKey("HabitatId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
